### ISSUE TITLE
Settings not being saved in GUI...container restart reverts to default values

### ISSUE THREAD

**Issue by Coder84619** [DasRaschloch/deemix-gui#2]
Using the latest build if I change any GUI settings, like download folder, and restart the container the new setting is lost. If I stop the container, manually edit the json config file (e.g. change download path), and start the container the filesystem config file is over written with defaults. So the container has write access to the file...it just keeps getting reset.

**Comment by DasRaschloch** [comment]
This occurs only for the download path. The rest of your settings should be fine. If you want to change where the container downloads files to, change the host-folder that is mapped to /downloads.
